import streamlit as st
st.title('streamlit demo')
st.header('This is header')
st.subheader('this is subheader')
st.markdown('___')
st.success('this is green')
st.error('this is red')
st.info('this is blue')
st.warning('this is yellow')
st.markdown('___')